from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable, Protocol

from .models import InferenceContext, PretrainedPrediction, ReviewRecord, SupervisedPrediction


class PretrainedDetectorPlugin(Protocol):
    def load(self, config: dict[str, Any]) -> None: ...
    def predict(self, image_path: Path, context: InferenceContext) -> PretrainedPrediction: ...
    def healthcheck(self) -> dict[str, Any]: ...
    def close(self) -> None: ...


class SupervisedDetectorPlugin(Protocol):
    def load(self, checkpoint: Path, config: dict[str, Any]) -> None: ...
    def predict(self, image_path: Path, context: InferenceContext) -> SupervisedPrediction: ...
    def close(self) -> None: ...


class ReviewProvider(Protocol):
    def export_review_batch(self, records: Iterable[dict[str, Any]], output: Path) -> Path: ...
    def import_review_result(self, path: Path) -> list[ReviewRecord]: ...
    def validate_review_record(self, record: ReviewRecord) -> None: ...

